name: qrt_env
channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - python=3.12
  - pip
  - pandas
  - numpy
  - seaborn
  - matplotlib
  - scikit-learn
  - lightgbm
  - xgboost
  - ipykernel
  - plotly
  - nbformat>=4.2.0
  - optuna
  - pip:
      - statsmodels
      - category_encoders
      - gradio
      - torch        # note: will likely be installed via pip or conda+channel below
